/*
 * File:   signalgeneration.c
 * Author: kjell.louagie
 *
 * Created on September 26, 2023, 10:17 AM
 */

#include "mcc_generated_files/pin_manager.h"
#include "signalgeneration.h"
#include "mcc_generated_files/oc1.h"
#include "video.h"
#include "string.h"
#include "stdlib.h"
#include "time.h"

#define BACKGROUND BLACK
#define FOREGROUND WHITE

int16_t state_buffer[60] = {0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0000, 0x0000,
                            0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0004, 0x0004,
                      0x0005, 0x0004, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000};


int16_t textbuffer[8][PIX_W] = {
    {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND},
{BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND}
};

/* Different state machine lines to print */
int16_t bufferLeft[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferRight[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferBoth[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferOnlyBall[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferLeftBall[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferRightBall[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};
int16_t bufferBothBall[PIX_W] = {BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,FOREGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND};



/* Starting state of game */
int16_t state[60] = {0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0004, 0x0004,
                      0x0005, 0x0004, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
                      0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000};


const int16_t zero[8][8] = {
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t one[8][8] = {
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t two[8][8] = {
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t three[8][8] = {
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t four[8][8] = {
{BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t five[8][8] = {
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t six[8][8] = {
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t seven[8][8] = {
{FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t eight[8][8] = {
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t nine[8][8] = {
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, FOREGROUND, FOREGROUND, FOREGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND},
{BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND, BACKGROUND}
};

const int16_t *numbers_ptr[] = {zero, one, two, three, four, five, six, seven, eight, nine, zero};

/* Pointers to support double state buffer */
//uint16_t *state_ptr = state_buffer;
//uint16_t *draw_ptr = state_buffer;
//uint16_t *second_state_ptr = state;
//
//
//uint16_t *current_ball_buffer = bufferBothBall;
//uint16_t *previous_ball_buffer = bufferBothBall;
//
///* Initiate global variables */
//uint16_t lines = 0;
//uint8_t effective_lines = 0;
//uint8_t refresh_count = 0;
//uint8_t score_1 = 0;
//uint8_t score_2 = 0;
//uint8_t *score_ptr;
//
//bool start = false;
//bool reset = false;
//bool set_score_1 = false;



// ball starts in the middle
struct ball ball = {SCREEN_CENTER_X, SCREEN_CENTER_Y, LEFT};

//// bars start in the middle
//uint8_t y_topposition_leftbar = SCREEN_CENTER_Y - 2;
//uint8_t y_topposition_rightbar = SCREEN_CENTER_Y - 2;




struct vga vga = {0, 0, 0, bufferBothBall, bufferBothBall, state_buffer, state_buffer, state};
struct game game = {0, 0, false, false, false, SCREEN_CENTER_Y - 2, SCREEN_CENTER_Y - 2};


/*
 * ########################################################
 * Interrupt handler for HSYNC signal
 * Line counting for VSYNC signal happens here
 * ########################################################
 */
void HSYNC(void)
{
    // Video generating here    
    vga.effective_lines = (vga.lines-35)/8;
    switch(vga.draw_ptr[vga.effective_lines])
    {
                case(0x0000):
                {
                    drawBackground((BACKGROUND));
                    break;
                }
                case(0x0001):
                {
                    asm("nop");
                    drawLine(textbuffer[vga.effective_lines]);
                    break;
                }
                case(0x0008):
                {
                    drawLine(bufferOnlyBall);
                    break;
                }
                case(0x0002):
                {
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop");
                    drawLine(bufferLeft);
                    break;
                } 
                case(0x0003):
                {
                    asm("nop");
                    drawLine(bufferRight);
                    break;
                }
                case(0x0004):
                {
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop");
                    drawLine(bufferBoth);
                    break;
                }
                case(0x0005):
                {
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    drawLine(bufferBothBall);
                    break;
                }
                case(0x0006):
                {
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop"); \
                    asm("nop");
                    drawLine(bufferLeftBall);
                    break;
                }
                case(0x0007):
                {
                    asm("nop"); \
                    asm("nop");
                    drawLine(bufferRightBall);
                    break;
                }
                default:
                {
                    // outside of screen
                    break;
                }
    }
    /* Set VSYNC high */
    if(vga.lines == SYNC_LINES) {_LATB7 = 1;}
    // End of line
    vga.lines++;
}


/* 
 * ########################################################
 * Interrupt handler for VSYNC after 16,7 ms (lines > 525)
 * Calculating the shown bitmap happens here
 * ########################################################
 */
void VSYNC(void)
{   
    // Vertical Sync (2 lines)
    IO_VSYNC_SetLow();
    if(_RA10 == 0) {game.start = true;}
    
        if ((vga.refresh_count == 3 && game.start))
        {
            vga.draw_ptr = vga.state_ptr;
            vga.previous_ball_buffer = BACKGROUND;
            calculateStates(&vga.draw_ptr, &game.y_topposition_leftbar, &game.y_topposition_rightbar, &ball);
            getBallBuffer(&vga.draw_ptr, &ball);
            if(!game.reset) vga.refresh_count = 6;       // if the score shouldn't change, jump back to beginning of loop
        }
        else if (vga.refresh_count == 2 && game.start)
        {
            //outOfBoundsHandler(&ball, &game, &vga);
        }
        else if (vga.refresh_count == 1 && game.start)
        {
            memset(&vga.second_state_ptr[34], 0x0000, 52);
            vga.state_ptr = (vga.state_ptr == state) ? state_buffer : state;
            vga.second_state_ptr = (vga.second_state_ptr == state_buffer) ? state : state_buffer;
            vga.previous_ball_buffer = &vga.current_ball_buffer[ball.x_position_ball];
            //moveBall(&ball);
            moveLeftBar(&game.y_topposition_leftbar);
            
        }
        else if (vga.refresh_count == 4)
        {   
            if(game.set_score_1) setNumber(textbuffer, numbers_ptr[game.score_1], 0, 4, 53);
            else setNumber(textbuffer, numbers_ptr[game.score_2], 0, 4, 19);
            
        }
        else if (vga.refresh_count == 5)
        {
            if(game.set_score_1) setNumber(textbuffer, numbers_ptr[game.score_1], 4, 7, 53);
            else setNumber(textbuffer, numbers_ptr[game.score_2], 4, 7, 19);
            game.reset = false;
        }
        else
        {
            memset(&vga.second_state_ptr[8], 0x0000, 52);
            //moveRightBar(&game.y_topposition_rightbar, &ball);
        }
    
    vga.lines = 0;
    vga.refresh_count = (vga.refresh_count < 5) ? vga.refresh_count + 1 : 0;
}

/* Control left bar with joystick */
static void moveLeftBar(int16_t *const y_topposition_leftbar)
{
    uint16_t VRY = ADC1_ConversionResultGet();
     if(VRY < 200 && *y_topposition_leftbar != 8)
     {
         (*y_topposition_leftbar)--;
     }
     else if (VRY > 800 && *y_topposition_leftbar != 55)
     {
         (*y_topposition_leftbar)++;
     }
}

/* Computer controlled right bar */
static void moveRightBar(int16_t *const y_topposition_rightbar, const struct ball *const ball)
{
    if(ball->y_position_ball > 10 && ball->y_position_ball < 58)
    {
        *y_topposition_rightbar = (ball->y_position_ball - 2);
    }
}


/*
 * Handles the score when a point is made
 * Handles when the ball hits a bar
 */
static void outOfBoundsHandler(struct ball *const ball, struct game *const game, struct vga *const vga)
{
    if (ball->x_position_ball == LEFTBAR_X) /* Ball has gone past left bar */
    {
        if((ball->y_position_ball >= game->y_topposition_leftbar && ball->y_position_ball < (game->y_topposition_leftbar + BARLENGTH)))
        {
            changeDirectionOnLeftBarHit(ball, game->y_topposition_leftbar);
        }
        else
        {
            game->reset = true;
            game->start = false;
            vga->refresh_count = 4;
            (game->score_1)++;
            if(game->score_1 == 10) {game->score_1 = 0; game->score_2 = 0;}
            ball->x_position_ball = SCREEN_CENTER_X;
            ball->y_position_ball = SCREEN_CENTER_Y;
            ball->direction = LEFT;
            game->y_topposition_leftbar = SCREEN_CENTER_Y - 2;
            game->y_topposition_rightbar = SCREEN_CENTER_Y - 2;
            vga->draw_ptr = vga->state_ptr;
            vga->previous_ball_buffer = BACKGROUND;
            calculateStates(vga->draw_ptr, game->y_topposition_leftbar, game->y_topposition_rightbar, ball);
            getBallBuffer(&vga->draw_ptr, ball);
            game->set_score_1 = true;
        }
    } else if (ball->x_position_ball == RIGHTBAR_X)
    {
        if(game->y_topposition_rightbar == 55) game->y_topposition_rightbar -= rand()%2;
        else game->y_topposition_rightbar += rand()%3 - 1;
        if ((ball->y_position_ball >= game->y_topposition_rightbar && ball->y_position_ball < (game->y_topposition_rightbar + BARLENGTH)))
        {
            changeDirectionOnRightBarHit(ball, game->y_topposition_rightbar);
        }
        else
        {
            game->reset = true;
            game->start = false;
            vga->refresh_count = 4;
            (game->score_2)++;
            if(game->score_2 == 10) {game->score_1 = 0; game->score_2 = 0;}
            ball->x_position_ball = SCREEN_CENTER_X;
            ball->y_position_ball = SCREEN_CENTER_Y;
            ball->direction = RIGHT;
            game->y_topposition_leftbar = SCREEN_CENTER_Y - 2;
            game->y_topposition_rightbar = SCREEN_CENTER_Y - 2;
            vga->draw_ptr = vga->state_ptr;
            vga->previous_ball_buffer = BACKGROUND;
            calculateStates(vga->draw_ptr, game->y_topposition_leftbar, game->y_topposition_rightbar, ball);
            getBallBuffer(&vga->draw_ptr, ball);
            game->set_score_1 = false;
        }
    }
    else if (ball->y_position_ball == 8 || ball->y_position_ball == 59)
    {
        calculateNewDirection(ball);
    }
}


/*
 * Redraw number over several times
 */
static void setNumber(uint16_t textbuffer[8][80], const uint16_t numberbuffer[8][8], uint8_t beginrow, uint8_t endrow, uint8_t position)
{
    for (beginrow; beginrow <= endrow; beginrow++)
    {
        memcpy(&textbuffer[beginrow][position], numberbuffer[beginrow], 8 * sizeof(uint16_t));
    }
}



/*
 * Determine the state of every line according to the current x- and y-coordinates
 * Draw the ball in the right buffer 
 */
static void calculateStates(uint16_t *const state, const uint8_t *const y_topposition_leftbar, const uint8_t *const y_topposition_rightbar, const struct ball *const ball)
{
    uint8_t non_overlap = abs(*y_topposition_leftbar - *y_topposition_rightbar);
    uint8_t overlap = BARLENGTH - non_overlap;
    int i = 0, k = 0;
    if(non_overlap < BARLENGTH) /* There is overlap */
    {
        if(*y_topposition_leftbar < *y_topposition_rightbar)  /* Left bar is higher */
        {
            for(i; i < non_overlap; i++)
            {
                state[*y_topposition_leftbar + i] = 0x0002;  /* Either left bar or left bar with ball */
                state[*y_topposition_rightbar + overlap + i] = 0x0003; /* Either right bar or TODO: right bar with ball */
            }
            for(k; k < overlap; k++)
            {
                state[*y_topposition_rightbar + k] = 0x0004; /* Either both bars or TODO: both bars and ball */
            }
        }
        else
        {
            for(i = 0; i < non_overlap; i++)
            {
                state[*y_topposition_rightbar + i] = 0x0003; /* Either right bar or TODO: right bar with ball */
                state[*y_topposition_leftbar + overlap + i] = 0x0002;
                
            }
            for(k = 0; k < overlap; k++)
            {
                state[*y_topposition_leftbar + k] = 0x0004; /* Either both bars or TODO: both bars and ball */
            }
        }
    }
    else  /* There is no overlap */
    {
        for(i = *y_topposition_leftbar; i < *y_topposition_leftbar + BARLENGTH; i++)
        {
            state[i] = 0x0002;
        }
        for (k = *y_topposition_rightbar; k < *y_topposition_rightbar + BARLENGTH; k++)
        {
            state[k] = 0x0003;
        }
    }
    /* If ball line is still in zero state, no bars are present */
    if (state[ball->y_position_ball] == 0x0000) 
    {
        state[ball->y_position_ball] =  0x0008;
        bufferOnlyBall[ball->x_position_ball] = FOREGROUND;
        vga.current_ball_buffer = bufferOnlyBall;
    }
}


/*
 * Set state of ball line and draw ball
 */
static void getBallBuffer(uint16_t *const state, const struct ball *const ball)
{
    switch(state[ball->y_position_ball])
    {
        case(0x0002):
        {
            state[ball->y_position_ball] = 0x0006;
            bufferLeftBall[ball->x_position_ball] = FOREGROUND;
            vga.current_ball_buffer = bufferLeftBall;
            break;
        }
        case(0x0003):
        {
            state[ball->y_position_ball] = 0x0007;
            bufferRightBall[ball->x_position_ball] = FOREGROUND;
            vga.current_ball_buffer = bufferRightBall;
            break;
        }
        case(0x0004):
        {
            state[ball->y_position_ball] = 0x0005;
            bufferBothBall[ball->x_position_ball] = FOREGROUND;
            vga.current_ball_buffer = bufferBothBall;
            break;
        }
    }
}

/*
 * Moves the ball 1 pixel in a direction of choice
 */
static void moveBall(struct ball *const ball)
{
    switch(ball->direction)
    {
        case(0x0000):
        {
            (ball->x_position_ball)--;
            break;
        }
        case(0x0001):
        {
            (ball->x_position_ball)++;
            break;
        }
        case(0x0002):
        {
            (ball->y_position_ball)--;
            break;
        }
        case(0x0003):
        {
            (ball->y_position_ball)++;
            break;
        }
        case(0x0004):
        {
            (ball->x_position_ball)--;
            (ball->y_position_ball)--;
            break;
        }
        case(0x0005):
        {
            (ball->x_position_ball)++;
            (ball->y_position_ball)++;
            break;
        }
        case(0x0006):
        {
            (ball->x_position_ball)--;
            (ball->y_position_ball)++;
            break;
        }
        case(0x0007):
        {
            (ball->x_position_ball)++;
            (ball->y_position_ball)--;
            break;
        }
    }
}


static void calculateNewDirection(struct ball *const ball)
{
    switch(ball->direction)
    {
        case(0x0000):
        {
            ball->direction = 0x0001;
            break;
        }
        case(0x0001):
        {
            ball->direction = 0x0000;
            break;
        }
        case(0x0004):
        {
            ball->direction = 0x0006;
            break;
        }
        case(0x0005):
        {
            ball->direction = 0x0007;
            break;
        }
        case(0x0006):
        {
            ball->direction = 0x0004;
            break;
        }
        case(0x0007):
        {
            ball->direction = 0x0005;
            break;
        }
    }
}

static void changeDirectionOnLeftBarHit(struct ball *const ball, int16_t y_topposition_leftbar)
{
    if(ball->y_position_ball == (y_topposition_leftbar + 2))
    {
        ball->direction = RIGHT;
    }
    else if(ball->y_position_ball >= y_topposition_leftbar && ball->y_position_ball < (y_topposition_leftbar + 2))
    {
        if(y_topposition_leftbar == 0) ball->direction = RIGHTDOWN;
        else ball->direction = RIGHTUP;
    }
    else
    {
        if(y_topposition_leftbar == 75) ball->direction = RIGHTUP;
        else ball->direction = RIGHTDOWN;
    }
}

static void changeDirectionOnRightBarHit(struct ball *const ball, int16_t y_topposition_rightbar)
{
    if(ball->y_position_ball == (y_topposition_rightbar + 2))
    {
        ball->direction = LEFT;
    }
    else if(ball->y_position_ball >= y_topposition_rightbar && ball->y_position_ball < (y_topposition_rightbar + 2))
    {
        if(y_topposition_rightbar == 0) ball->direction = LEFTDOWN;
        else ball->direction = LEFTUP;
    }
    else
    {
        if(y_topposition_rightbar == 75) ball->direction = LEFTUP;
        else ball->direction = LEFTDOWN;
    }
}
